# HPA (Horizontal Pod Autoscaler): Automatically scales the number of pods based on CPU usage
# - When CPU > 70%, it adds more pods
# - When CPU is low, it scales down (minimum 2 pods)
# - Needs metrics-server (components.yaml) to read CPU %
# - Works with Cluster Autoscaler: HPA creates pods, Cluster Autoscaler creates nodes to fit them
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: health-service-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-service

  minReplicas: 2
  maxReplicas: 10

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
