apiVersion: v1
kind: Service

metadata:
  name: health-service
  labels:
    app: health-service
  annotations:
    # Use NLB instead of Classic ELB for better performance
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    # SSL Certificate from ACM
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:307218864628:certificate/2d4d0694-a3fe-49cf-9412-233e82848c89"

    # Enable SSL on port 443
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

    # Modern SSL policy (TLS 1.2+)
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"

spec:
  type: LoadBalancer

  selector:
    app: health-service

  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
