# ServiceMonitor for NGINX Ingress Controller
# Enables Prometheus to scrape nginx metrics for KEDA scaling
#
# Apply with: kubectl apply -f nginx-servicemonitor.yaml

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: controller
    release: prometheus  # Must match Prometheus Helm release name
spec:
  # Which namespaces to look for Services
  namespaceSelector:
    matchNames:
      - ingress-nginx

  # Which Services to monitor (by label)
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller

  # Endpoints to scrape
  endpoints:
    - port: metrics           # Port name from nginx service
      interval: 15s
      path: /metrics
      scheme: http

      # Relabeling to add useful labels
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod

---
# PodMonitor alternative (if service doesn't expose metrics port)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress-controller-pods
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nginx-ingress
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx

  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller

  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics

---
# ServiceMonitor for health-service application metrics
# (if your app exposes Prometheus metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-service
  namespace: monitoring
  labels:
    app: health-service
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default

  selector:
    matchLabels:
      app: health-service

  endpoints:
    - port: http           # Assuming your service exposes metrics on the http port
      interval: 15s
      path: /metrics        # Change if your app uses different path
      scheme: http
